### ISSUE TITLE
Error Parsing substitutions

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#142]
https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/35111a0b04875f6761794eec8a0c5674dc5e021c
```
java.lang.Exception: RangeError (length): Invalid value: Only valid value is 0: 1

#0      ListBase.indexOf (dart:collection/list.dart)
#1      SPHclient.getVplanNonJSON (package:sph_plan/client/client.dart:342)
<asynchronous suspension>
#2      SubstitutionsFetcher._get (package:sph_plan/client/fetcher.dart:85)
<asynchronous suspension>
#3      Fetcher.fetchData.<anonymous closure> (package:sph_plan/client/fetcher.dart:57)
<asynchronous suspension>

at ly.count.dart.countly_flutter.CountlyFlutterPlugin.onMethodCall(Unknown Source:742)
at c4.k$a.a(Unknown Source:17)
at p3.c.l(Unknown Source:18)
at p3.c.m(Unknown Source:40)
at p3.c.i(Unknown Source:0)
at p3.b.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by CodeSpoof** [comment]
Kann ich nicht reproduzieren. Betroffener Abschnitt:
```
var entry = {
          "Stunde": headers.contains("Stunde") ? fields[headers.indexOf("Stunde")].text.trim() : "",
          "Klasse": headers.contains("Klasse") ? fields[headers.indexOf("Klasse")].text.trim() : "",
          "Vertreter": headers.contains("Vertretung") ? fields[headers.indexOf("Vertretung")].text.trim() : "",
          "Lehrer": headers.contains("Lehrer") ? fields[headers.indexOf("Lehrer")].text.trim() : "",
          "Art": headers.contains("Art") ? fields[headers.indexOf("Art")].text.trim() : "",
          "Fach": headers.contains("Fach") ? fields[headers.indexOf("Fach")].text.trim() : "",
          "Raum": headers.contains("Raum") ? fields[headers.indexOf("Raum")].text.trim() : "",
          "Hinweis": headers.contains("Hinweis") ? fields[headers.indexOf("Hinweis")].text.trim() : "",
          "Tag_en": parsedDate.format('yyyy-MM-dd')
        };
```

Die Zeile für das Parsen der Stunde ist die, die im Stacktrace auftaucht. Ist der Fehler bei dir aufgetreten (gibt es HTML dazu) oder kannst du ihn reproduzieren?

**Comment by alessioC42** [comment]
Ich glaube, der Fehler tritt auf, wenn es keine Einträge gibt. Ich kann es im Moment nicht testen, aber das wird bei mir zurückgegeben. Der normale Filter funktioniert bei mir nicht.
[page.html.txt](https://github.com/alessioC42/lanis-mobile/files/14043077/page.html.txt)
