### ISSUE TITLE
Mein Untericht Bug 

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#70]
Die "Mein Unterricht" Seite lädt unendlich lange und es kommt nie ein Ergebnis. (Bei allen drei unter Gruppen)

Wenn bei "Lademodus" in den Einstellungen "Alles laden" einstellt und die App neu startet, ist man im Ladebildschirm gefangen.

Wenn ich es in Android Studio teste bekomme ich diesen fehler:

I/flutter (10759): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (10759): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (10759): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (10759): #1      SPHclient.getMeinUnterrichtOverview.<anonymous closure> (package:sph_plan/client/client.dart:577:65)
I/flutter (10759): #2      SPHclient.getMeinUnterrichtOverview (package:sph_plan/client/client.dart:587:6)
I/flutter (10759): <asynchronous suspension>
I/flutter (10759): #3      Fetcher.fetchData.<anonymous closure> (package:sph_plan/client/fetcher.dart:56:19)
I/flutter (10759): <asynchronous suspension>
I/flutter (10759): ----------------------------------------------------
W/FirebaseCrashlytics(10759): Unable to read App Quality Sessions session id.

**Comment by baum-eule** [comment]
Es könnte daran liegen, dass bei mir ein Eintrag bei "Ein Unterricht" keinen Inhalt und nur eine Überschrift hat.
Oder es könnte daran liegen, dass bei mir ein Eintrag nur "noch kein Eintrag" stehen hat.
